[package]
name = "syncnotes-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.35"
egui = "0.35"
reqwest = { version = "0.12", features = ["json", "blocking", "rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = { version = "0.17", default-features = false }
auto-launch = "0.6"
dirs = "6"
image = "0.25"
